@baseUrl = http://localhost:8080

### Create a new customer
POST {{baseUrl}}/customers
Content-Type: application/json

{
  "firstName": "Heitor",
  "lastName": "Castanet",
  "cpf": "332.233.113-00",
  "birthDate": "1999-12-31",
  "phone": "+55 32 42521-3213",
  "email": "castanh222a@email.com"
}

### Get all customers with pagination
GET {{baseUrl}}/customers?page=0&size=10&sort=lastName,asc
Content-Type: application/json

### Get a customer by ID
GET {{baseUrl}}/customers/8
Content-Type: application/json

### Update a customer by ID
PUT {{baseUrl}}/customers/4
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "cpf": "123.456.789-00",
    "birthDate": "1990-01-01",
    "phone": "+55 22225-7890",
    "email": "newEmailJohn@email.com"
}

### Delete a customer by ID
DELETE {{baseUrl}}/customers/1
Content-Type: application/json

### Create invalid customer (duplicate CPF or email)
POST {{baseUrl}}/customers
Content-Type: application/json

{
  "firstName": "Heitor",
  "lastName": "Castanet",
  "cpf": "332.233.113-00",
  "birthDate": "1999-12-31",
  "phone": "+55 32 42521-3213",
  "email": "castanha123@email.com"
}

### Create invalid customer (Missing required fields)
POST {{baseUrl}}/customers
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "cpf": "",
  "birthDate": "",
  "phone": "",
  "email": "invalidEmailFormat"
}